### ISSUE TITLE
Put some threshold

### ISSUE THREAD

**Issue by DanielLampa** [MaryM-C/FISDA#13]
Set a specific threshold to determine whether the user's image belongs to the dataset. You can limit this by checking if the maximum prediction is less than 50% OR 60%. If the user provides incorrect input, the app must display the following tips:

1. The image must not be included in the dataset.
2. The image must have good lighting.
3. etc.

**Comment by MaryM-C** [comment]
the commit 3f4f429 has fix this issue. With the threshold of 60% confidence
