### ISSUE TITLE
Some information not showing

### ISSUE THREAD

**Issue by DanielLampa** [MaryM-C/FISDA#7]
The temperature for some fish are not showing

**Comment by MaryM-C** [comment]
A minor typo led to the absence of temperature data for certain fish entries. Specifically, some entries were labeled as 'Temperature ' (with an extra space), while others were correctly labeled as 'Temperature'. I have addressed this issue by correcting the labeling in the Firebase database.

**Comment by DanielLampa** [comment]
Thank you for the update! It's good to know that you've identified and addressed the issue with the temperature data in our fish database. It's amazing how a minor typo like an extra space can cause such discrepancies hahahahaha.
